project:
  type: website
  output-dir: docs

website:
  title: "My Learning Diary RS site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - docs/ld_week_2.qmd
      - docs/week_4_policy.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

